services:
    app_configuration_listkdo:
        class: AppBundle\Doctrine\Configuration\ConfigurationListKdo
        arguments:
            - @app_entity_listkdo
            - %formtypelistkdo%

    app_configuration_userlistkdo:
        class: AppBundle\Doctrine\Configuration\ConfigurationUserListKdo
        arguments:
            - @app_entity_userlistkdo
            - %formtypeuserlistkdo%
