services:
    app_entity_listkdo:
        class: AppBundle\Entity\ListKdo
    app_entity_userlistkdo:
        class: AppBundle\Entity\UserListKdo
    app_entity_kdo:
        class: AppBundle\Entity\Kdo
    app_entity_userkdo:
        class: AppBundle\Entity\UserKdo
