parameters:
    formtypelistkdo: appbundle_listkdo_formtype
    formtypeuserlistkdo: appbundle_userlistkdo_formtype
    formtypekdo: appbundle_kdo_formtype

services:
    app_form_listkdo:
        class: AppBundle\Form\Type\ListKdoType
        arguments: [ @app_manager_listkdo, @security.context ]
        tags:
            - { name: form.type, alias: %formtypelistkdo% }
    app_form_userlistkdo:
        class: AppBundle\Form\Type\UserListKdoType
        arguments: [ @app_manager_userlistkdo, @security.context ]
        tags:
            - { name: form.type, alias: %formtypeuserlistkdo% }
    app_form_kdo:
        class: AppBundle\Form\Type\KdoType
        arguments: [ @app_manager_kdo, @security.context ]
        tags:
            - { name: form.type, alias: %formtypekdo% }
