services:
    app.listener.listkdo:
        class: AppBundle\EventListener\ListKdoListener
        arguments: [ @doctrine.orm.entity_manager, @security.context ]
        tags:
            - { name: kernel.event_subscriber, priority: 254 }
    app.listener.kdo:
        class: AppBundle\EventListener\KdoListener
        arguments: [ @doctrine.orm.entity_manager, @security.context ]
        tags:
            - { name: kernel.event_subscriber, priority: 254 }
    app.listener.userkdo:
        class: AppBundle\EventListener\UserKdoListener
        arguments: [ @doctrine.orm.entity_manager, @security.context, @event_dispatcher, @app.event.kdo ]
        tags:
            - { name: kernel.event_subscriber, priority: 254 }