services:
    app_manager_listkdo:
        class: AppBundle\Doctrine\ListKdoManager
        arguments:
            - @doctrine.orm.entity_manager
            - @app_configuration_listkdo

    app_manager_userlistkdo:
        class: AppBundle\Doctrine\UserListKdoManager
        arguments:
            - @doctrine.orm.entity_manager
            - @app_configuration_userlistkdo

    app_manager_kdo:
        class: AppBundle\Doctrine\KdoManager
        arguments:
            - @doctrine.orm.entity_manager
            - @app_configuration_kdo
