services:
    app.security.access.listkdoaction_voter:
        class:      AppBundle\Security\Authorization\Voter\ListKdoAccessActionVoter
        arguments: [ @doctrine.orm.entity_manager, @security.access.role_hierarchy_voter ]
        public:     false
        tags:
           - { name: security.voter }