<?php

namespace AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Security\Core\SecurityContext;
use ZIMZIM\ToolsBundle\Model\APYDataGrid\ApyDataGridRepositoryInterface;
use APY\DataGridBundle\Grid\Source\Entity;

/**
 * KdoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KdoRepository extends EntityRepository implements ApyDataGridRepositoryInterface
{
    public function getList(Entity $source, SecurityContext $securityContext)
    {
        return $source;
    }
}
