<?php

namespace AppBundle\Entity\Repository;

use APY\DataGridBundle\Grid\Source\Entity;
use Doctrine\ORM\EntityRepository;
use Symfony\Component\Security\Core\SecurityContext;
use ZIMZIM\ToolsBundle\Model\APYDataGrid\ApyDataGridRepositoryInterface;

/**
 * ListKdoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListKdoRepository extends EntityRepository implements ApyDataGridRepositoryInterface
{
    public function getList(Entity $source, SecurityContext $securityContext)
    {
        return $source;
    }

    public function getListByDate(\DateTime $date = null)
    {
        $query = $this->createQueryBuilder('lk');

        if(isset($date)){
            $query->where('lk.date >= :date')
                ->setParameter('date', $date->format('Y-m-d'));
        }
        $query->orderBy('lk.date', 'DESC');
        $query->setMaxResults(10);

        return $query->getQuery()->getResult();
    }
}