<?php

namespace AppBundle\Entity\Repository;

use AppBundle\Entity\ListKdo;
use AppBundle\Entity\User;
use APY\DataGridBundle\Grid\Source\Entity;
use Doctrine\ORM\EntityRepository;
use ZIMZIM\ToolsBundle\Model\APYDataGrid\ApyDataGridRepositoryInterface;

/**
 * ListKdoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserListKdoRepository extends EntityRepository implements ApyDataGridRepositoryInterface
{
    public function getList(Entity $source)
    {
        return $source;
    }


    public function getAccessUser(ListKdo $listKdo, User $user)
    {

        $query = $this->createQueryBuilder('ulk');

        $query->where('ulk.listKdo = :listkdo')
            ->andWhere('ulk.user = :user')
            ->setParameter('listkdo', $listKdo)
            ->setParameter('user', $user);

        return $query->getQuery()->getOneOrNullResult();

    }

}