appbundle_kdo:
    path:     /
    defaults: { _controller: "AppBundle:Kdo:index" }

appbundle_kdo_show:
    path:     /{id}/show/
    defaults: { _controller: "AppBundle:Kdo:show" }

appbundle_kdo_new:
    path:     /new/
    defaults: { _controller: "AppBundle:Kdo:new" }

appbundle_kdo_create:
    path:     /create/
    defaults: { _controller: "AppBundle:Kdo:create" }
    methods:  POST

appbundle_kdo_create_listkdo:
    path:     /create/{id}/
    defaults: { _controller: "AppBundle:Kdo:create" }
    methods:  POST|GET
    requirements:
        id: \d+

appbundle_kdo_edit:
    path:     /{id}/edit/
    defaults: { _controller: "AppBundle:Kdo:edit" }

appbundle_kdo_update:
    path:     /{id}/update/
    defaults: { _controller: "AppBundle:Kdo:update" }
    methods:  [POST, PUT]

appbundle_kdo_delete:
    path:     /{id}/delete/
    defaults: { _controller: "AppBundle:Kdo:delete" }
    methods:  [POST, DELETE]
