appbundle_listkdo_list:
    path:     /
    defaults: { _controller: "AppBundle:ListKdo:list" }

appbundle_listkdo_slug:
    path:     /{slug}/
    defaults: { _controller: "AppBundle:ListKdo:slug" }
    requirements:
        slug: ^[a-z\-]+$

appbundle_listkdo_listnew:
    path:     /listnew/
    defaults: { _controller: "AppBundle:ListKdo:listnew" }
    methods:  [GET, POST]

appbundle_listkdo_getaccess:
    path:     /{id}/getaccess/
    defaults: { _controller: "AppBundle:ListKdo:getaccesslistkdo" }
    methods:  [GET, POST]