app_app_kdo:
    resource: "@AppBundle/Resources/config/routing/admin_kdo.yml"
    prefix:   /kdo/

app_appbundle_userlistkdo:
    resource: "@AppBundle/Resources/config/routing/admin_userlistkdo.yml"
    prefix:   /userlistkdo/

app_appbundle_listkdo:
    resource: "@AppBundle/Resources/config/routing/listkdo.yml"
    prefix:   /

app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Home:index }
