app_appbundle_userlistkdo:
    resource: "@AppBundle/Resources/config/routing/admin_userlistkdo.yml"
    prefix:   /userlistkdo/

app_appbundle_admin_listkdo:
    resource: "@AppBundle/Resources/config/routing/admin_listkdo.yml"
    prefix:   /listkdo/

app_appbundle_listkdo:
    resource: "@AppBundle/Resources/config/routing/listkdo.yml"
    prefix:   /kdo/

app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Home:index }
