app_appbundle_userkdo:
    resource: "@AppBundle/Resources/config/routing/userkdo.yml"
    prefix:   /userkdo/

app_appbundle_kdo:
    resource: "@AppBundle/Resources/config/routing/kdo.yml"
    prefix:   /kdo/

app_appbundle_userlistkdo:
    resource: "@AppBundle/Resources/config/routing/userlistkdo.yml"
    prefix:   /userlistkdo/

app_appbundle_listkdo:
    resource: "@AppBundle/Resources/config/routing/listkdo.yml"
    prefix:   /

app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Home:index }
