imports:
    - { resource: service/manager.yml }
    - { resource: service/config.yml }
    - { resource: service/form.yml }
    - { resource: service/entity.yml }
    - { resource: service/event.yml }
    - { resource: service/listener.yml }
    - { resource: service/security.yml }
